### PR TITLE
Revert "moved search bar to title bottom"

### PR DESCRIPTION
**Pull request by MyatThuKo**
Reverts eliboss/search-savior#47

### CODE REVIEW

**Comment by MyatThuKo** [comment]
@Godwindaniel10 Sorry I misread your last comment and thought it was done. I approved your pull request and merge it already. I am not sure if this revert will allow you to work on the issue. Please let me know. Thanks!

**Comment by godwin-morwin** [comment]
@MyatThuKo yeah , I will surely work on the issue☑️

**Comment by godwin-morwin** [comment]
oops! not working. i think you should create an issue on that.

the issue is ( submit-search button is at an absolute position, so if the search box is clicked, the cancel icon will lap on the submit search button, which is very bad, and I apologize for that.

**Comment by elleanne** [comment]
@Godwindaniel10 I reopened the issue. Is that what you were asking? https://github.com/eliboss/search-savior/issues/42

**Comment by godwin-morwin** [comment]
Yes , exactly

**Comment by elleanne** [comment]
I think this PR can be closed. I submitted a new one #52 that should fix the overlapping issue. (I just changed the positioning so that the search button is below the search text form)

**Comment by godwin-morwin** [comment]
@eliboss awesome! Thanks for solving the issue. 😊

**Comment by elleanne** [comment]
Already solved with a different branch.

**Pull request closed without merging**
